package com.luisusr.demopruebas.model;
// Generated Nov 28, 2017 10:50:26 AM by Hibernate Tools 5.1.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BonusId generated by hbm2java
 */
@Embeddable
public class BonusId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String ename;
	private String job;
	private BigDecimal sal;
	private BigDecimal comm;

	public BonusId() {
	}

	public BonusId(String ename, String job, BigDecimal sal, BigDecimal comm) {
		this.ename = ename;
		this.job = job;
		this.sal = sal;
		this.comm = comm;
	}

	@Column(name = "ENAME", length = 10)
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	@Column(name = "JOB", length = 9)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@Column(name = "SAL", precision = 22, scale = 0)
	public BigDecimal getSal() {
		return this.sal;
	}

	public void setSal(BigDecimal sal) {
		this.sal = sal;
	}

	@Column(name = "COMM", precision = 22, scale = 0)
	public BigDecimal getComm() {
		return this.comm;
	}

	public void setComm(BigDecimal comm) {
		this.comm = comm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BonusId))
			return false;
		BonusId castOther = (BonusId) other;

		return ((this.getEname() == castOther.getEname()) || (this.getEname() != null && castOther.getEname() != null
				&& this.getEname().equals(castOther.getEname())))
				&& ((this.getJob() == castOther.getJob()) || (this.getJob() != null && castOther.getJob() != null
						&& this.getJob().equals(castOther.getJob())))
				&& ((this.getSal() == castOther.getSal()) || (this.getSal() != null && castOther.getSal() != null
						&& this.getSal().equals(castOther.getSal())))
				&& ((this.getComm() == castOther.getComm()) || (this.getComm() != null && castOther.getComm() != null
						&& this.getComm().equals(castOther.getComm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEname() == null ? 0 : this.getEname().hashCode());
		result = 37 * result + (getJob() == null ? 0 : this.getJob().hashCode());
		result = 37 * result + (getSal() == null ? 0 : this.getSal().hashCode());
		result = 37 * result + (getComm() == null ? 0 : this.getComm().hashCode());
		return result;
	}

}
