package com.luisusr.demopruebas.model;
// Generated Nov 28, 2017 10:50:26 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Datos generated by hbm2java
 */
@Entity
@Table(name = "DATOS", schema = "POW_REP")
public class Datos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idData;
	private Date FRegistro;
	private String descripcion;

	public Datos() {
	}

	public Datos(Long idData, Date FRegistro, String descripcion) {
		this.idData = idData;
		this.FRegistro = FRegistro;
		this.descripcion = descripcion;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "SEQ_DATOS")
	@SequenceGenerator(name="SEQ_DATOS", sequenceName = "SEQ_DATOS", allocationSize=1)
	@Column(name = "ID_DATA", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getIdData() {
		return this.idData;
	}

	public void setIdData(Long idData) {
		this.idData = idData;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "F_REGISTRO", nullable = false, length = 7)
	public Date getFRegistro() {
		return this.FRegistro;
	}

	public void setFRegistro(Date FRegistro) {
		this.FRegistro = FRegistro;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
