package com.luisusr.demopruebas.model;
// Generated Nov 28, 2017 10:50:26 AM by Hibernate Tools 5.1.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Salgrade generated by hbm2java
 */
@Entity
@Table(name = "SALGRADE", schema = "POW_REP")
public class Salgrade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SalgradeId id;

	public Salgrade() {
	}

	public Salgrade(SalgradeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "grade", column = @Column(name = "GRADE", precision = 22, scale = 0)),
			@AttributeOverride(name = "losal", column = @Column(name = "LOSAL", precision = 22, scale = 0)),
			@AttributeOverride(name = "hisal", column = @Column(name = "HISAL", precision = 22, scale = 0)) })
	public SalgradeId getId() {
		return this.id;
	}

	public void setId(SalgradeId id) {
		this.id = id;
	}

}
